import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ridiBatang = localFont({
  src: "../public/fonts/RIDIBatang.otf",
  variable: "--font-ridi",
});

export const metadata: Metadata = {
  title: "쟌이 사주 도우미",
  description: "Generated by create next app",
};

export const viewport = {
  width: 1400,
  initialScale: 0.25,
  maximumScale: 1,
  userScalable: true,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${ridiBatang.variable} h-full antialiased`}
    >
      <body
        className="min-h-full flex flex-col overflow-x-auto"
        style={{
          fontFamily: "var(--font-ridi)",
        }}
      >
        {children}
      </body>
    </html>
  );
}